#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("IvaApp.Droid.Resource", IsApplication=true)]

namespace IvaApp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::IvaApp.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::IvaApp.Droid.Resource.String.Hello;
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::IvaApp.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::IvaApp.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int adjust4 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int cancel = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int cart = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int check = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int disk = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int fondo = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int key = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int key182 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int like = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int logoIvaApp = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int logoIvaApp30 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int logoIvaAppBlanco = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int math = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int power = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int refresh = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int rubbish = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int slideout = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int user = 2130837523;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040000
			public const int CustomTheme = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
